version: '2'
services:
    expenses-app:
        image: expenses
        external_links:
            - expenses-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=expenses
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    expenses-mongodb:
        extends:
            file: mongodb.yml
            service: expenses-mongodb
