version: '2'
services:
    expenses-mongodb:
        container_name: expenses-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/expenses/mongodb/:/data/db/
